### ISSUE TITLE
Huggingface hub error and imiginator weight error

### ISSUE THREAD

**Issue by zhuzhuhao-stf** [Zhoues/MineDreamer#4]
Hi, I followed the setup instruction and when I run the `bash scripts/inference_MineDreamer.sh` I have following error showed up:
```bash
Traceback (most recent call last):
  File "/home/miniconda3/envs/imaginator/lib/python3.9/site-packages/peft/utils/config.py", line 177, in _get_peft_type
    config_file = hf_hub_download(
  File "/home/user/miniconda3/envs/imaginator/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/user/miniconda3/envs/imaginator/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/user/miniconda3/envs/imaginator/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'data/weights/minedreamer/imaginator/LLM-20000'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Desktop/zhuzhuhao/minedreamer_stuff/MineDreamer/imaginator/test/inference_single_image_MLLMSD.py", line 223, in <module>
    main()
  File "/home/users/Desktop/zhuzhuhao/minedreamer_stuff/MineDreamer/imaginator/test/inference_single_image_MLLMSD.py", line 81, in main
    model_.model = PeftModel_for_LLM.from_pretrained(model_.model, LLM_sub_dir, adapter_name=adapter_name)
  File "/home/user/Desktop/zhuzhuhao/minedreamer_stuff/MineDreamer/imaginator/test/PeftForLoRA.py", line 261, in from_pretrained
    PeftConfig._get_peft_type(
  File "/home/user/miniconda3/envs/imaginator/lib/python3.9/site-packages/peft/utils/config.py", line 183, in _get_peft_type
    raise ValueError(f"Can't find '{CONFIG_NAME}' at '{model_id}'")
ValueError: Can't find 'adapter_config.json' at 'data/weights/minedreamer/imaginator/LLM-20000'

```

I guess the huggingface error is related to the huggingface version (I'm using `huggingface-hub 0.25.0`). So I wonder what version you're using? for the second error I don't know why it occured. Does the weighting downloading part should have also install the `imaginator` weights under `data/mindreamer/imaginator` folder? I didn't find any commands related to it among all he scripts.

Thx

**Comment by Zhoues** [comment]
@zhuzhuhao-stf 

For the first issue, you might try downgrading the `huggingface-hub` version. Since this work was produced during my internship at Shanghai AI Lab, and I have since left the position, I cannot specify the exact version of the package. However, lowering the version should likely resolve the issue.

Regarding the second issue, did you use the automatic download command from the README.md, specifically `download_minedreamer_weights.sh`? First, ensure that the `adapter_config.json` file exists, then verify the correctness of the file path. If the instructions are followed correctly, such issues should not occur. All weights should be downloaded to `data/weights` and should not be present in the `imaginator` directory. This issue may also result from the `huggingface-hub` version?
